// galary fully

var ElementorProFrontendConfig = {
    ajaxurl: "https:\/\/imtadhaka.com\/wp-admin\/admin-ajax.php",
    nonce: "ec9d1f4b60",
    urls: { assets: "https:\/\/imtadhaka.com\/wp-content\/plugins\/elementor-pro\/assets\/", rest: "https:\/\/imtadhaka.com\/wp-json\/" },
    shareButtonsNetworks: {
        facebook: { title: "Facebook", has_counter: !0 },
        twitter: { title: "Twitter" },
        linkedin: { title: "LinkedIn", has_counter: !0 },
        pinterest: { title: "Pinterest", has_counter: !0 },
        reddit: { title: "Reddit", has_counter: !0 },
        vk: { title: "VK", has_counter: !0 },
        odnoklassniki: { title: "OK", has_counter: !0 },
        tumblr: { title: "Tumblr" },
        digg: { title: "Digg" },
        skype: { title: "Skype" },
        stumbleupon: { title: "StumbleUpon", has_counter: !0 },
        mix: { title: "Mix" },
        telegram: { title: "Telegram" },
        pocket: { title: "Pocket", has_counter: !0 },
        xing: { title: "XING", has_counter: !0 },
        whatsapp: { title: "WhatsApp" },
        email: { title: "Email" },
        print: { title: "Print" },
    },
    facebook_sdk: { lang: "en_US", app_id: "" },
    lottie: { defaultAnimationUrl: "https:\/\/imtadhaka.com\/wp-content\/plugins\/elementor-pro\/modules\/lottie\/assets\/animations\/default.json" },
};

var elementorFrontendConfig = {
    environmentMode: { edit: !1, wpPreview: !1, isScriptDebug: !1 },
    i18n: {
        shareOnFacebook: "Share on Facebook",
        shareOnTwitter: "Share on Twitter",
        pinIt: "Pin it",
        download: "Download",
        downloadImage: "Download image",
        fullscreen: "Fullscreen",
        zoom: "Zoom",
        share: "Share",
        playVideo: "Play Video",
        previous: "Previous",
        next: "Next",
        close: "Close",
        a11yCarouselWrapperAriaLabel: "Carousel | Horizontal scrolling: Arrow Left & Right",
        a11yCarouselPrevSlideMessage: "Previous slide",
        a11yCarouselNextSlideMessage: "Next slide",
        a11yCarouselFirstSlideMessage: "This is the first slide",
        a11yCarouselLastSlideMessage: "This is the last slide",
        a11yCarouselPaginationBulletMessage: "Go to slide",
    },
    is_rtl: !1,
    breakpoints: { xs: 0, sm: 480, md: 768, lg: 1025, xl: 1440, xxl: 1600 },
    responsive: {
        breakpoints: {
            mobile: { label: "Mobile Portrait", value: 767, default_value: 767, direction: "max", is_enabled: !0 },
            mobile_extra: { label: "Mobile Landscape", value: 880, default_value: 880, direction: "max", is_enabled: !1 },
            tablet: { label: "Tablet Portrait", value: 1024, default_value: 1024, direction: "max", is_enabled: !0 },
            tablet_extra: { label: "Tablet Landscape", value: 1200, default_value: 1200, direction: "max", is_enabled: !1 },
            laptop: { label: "Laptop", value: 1366, default_value: 1366, direction: "max", is_enabled: !1 },
            widescreen: { label: "Widescreen", value: 2400, default_value: 2400, direction: "min", is_enabled: !1 },
        },
    },
    version: "3.23.4",
    is_static: !1,
    experimentalFeatures: {
        e_optimized_css_loading: !0,
        additional_custom_breakpoints: !0,
        container_grid: !0,
        e_swiper_latest: !0,
        e_nested_atomic_repeaters: !0,
        e_onboarding: !0,
        theme_builder_v2: !0,
        home_screen: !0,
        "ai-layout": !0,
        "landing-pages": !0,
        e_lazyload: !0,
        "page-transitions": !0,
        notes: !0,
        "form-submissions": !0,
        e_scroll_snap: !0,
    },
    urls: { assets: "https:\/\/imtadhaka.com\/wp-content\/plugins\/elementor\/assets\/", ajaxurl: "https:\/\/imtadhaka.com\/wp-admin\/admin-ajax.php" },
    nonces: { floatingButtonsClickTracking: "ca3fc27697" },
    swiperClass: "swiper",
    settings: { page: [], editorPreferences: [] },
    kit: {
        active_breakpoints: ["viewport_mobile", "viewport_tablet"],
        global_image_lightbox: "yes",
        lightbox_enable_counter: "yes",
        lightbox_enable_fullscreen: "yes",
        lightbox_enable_zoom: "yes",
        lightbox_enable_share: "yes",
        lightbox_title_src: "title",
        lightbox_description_src: "description",
    },
    post: { id: 5, title: "International%20Maritime%20Training%20Academy", excerpt: "", featuredImage: !1 },
};


